In [1]:
import pandas as pd
import os

from pathlib import Path

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Iterable, Optional

import numpy as np
import pandas as pd

## load embeddings

In [ ]:
# RQ
emb_sim_file="cosine_sim_mat_RNAquarium_second_to_last_layer.csv" 
emb_sim_dir = "cosine_similarity_matrices"
emb_sim_file_path = Path().cwd().parent / emb_sim_dir / emb_sim_file
RQ_sim_df = pd.read_csv(emb_sim_file_path, index_col=0)
print(emb_sim_file_path)

emb_sim_file="cosine_sim_mat_RNAquarium_randomized_second_to_last_layer.csv" 
emb_sim_file_path = Path().cwd().parent / emb_sim_dir / emb_sim_file
RQ_randomized_sim_df = pd.read_csv(emb_sim_file_path, index_col=0)
print(emb_sim_file_path)

/path/to/Geneformer_RQfork/embeddings/cosine_similarity_matrices/cosine_sim_mat_RNAquarium_second_to_last_layer.csv
/path/to/Geneformer_RQfork/embeddings/cosine_similarity_matrices/cosine_sim_mat_RNAquarium_randomized_second_to_last_layer.csv

In [3]:
RQ_sim_df.head()

,rpl24,cep97,nfkbiz,eed,hikeshi,tmem39a,ildr1a,gpa33a,dusp27,wu:fj30f06,...,COX2,ATP8,ATP6,COX3,ND3,ND4L,ND4,ND5,ND6,CYTB
rpl24,1.000000,0.272959,0.235549,0.256754,0.205985,0.257079,0.216786,0.234247,0.160970,0.083065,...,0.197968,0.090356,0.325535,0.190704,0.279971,0.102425,0.277884,0.191000,0.349950,0.195059
cep97,0.272959,1.000000,0.286664,0.500152,0.379980,0.506948,0.411913,0.271558,0.274397,0.297514,...,0.177957,0.153296,0.237179,0.242064,0.345656,0.178980,0.212455,0.219565,0.330471,0.255201
nfkbiz,0.235549,0.286664,1.000000,0.275793,0.407547,0.314703,0.447633,0.408331,0.308351,0.366558,...,0.240941,0.218963,0.270685,0.273476,0.201760,0.206829,0.292522,0.183763,0.240630,0.244379
eed,0.256754,0.500152,0.275793,1.000000,0.466804,0.576229,0.353269,0.194613,0.186875,0.197023,...,0.191992,0.176461,0.223793,0.195105,0.271937,0.168431,0.187971,0.188030,0.242384,0.173169
hikeshi,0.205985,0.379980,0.407547,0.466804,1.000000,0.347512,0.434054,0.237139,0.224556,0.181002,...,0.264463,0.119351,0.209098,0.205664,0.269856,0.130229,0.184434,0.162053,0.219775,0.188669

In [4]:
RQ_randomized_sim_df.head()

,rpl24,cep97,nfkbiz,eed,hikeshi,tmem39a,ildr1a,gpa33a,dusp27,wu:fj30f06,...,COX2,ATP8,ATP6,COX3,ND3,ND4L,ND4,ND5,ND6,CYTB
rpl24,1.000000,0.317180,0.185087,0.053960,0.175326,0.647515,0.248803,-0.049734,0.050452,0.333339,...,0.270470,0.176277,-0.028960,0.295828,0.080626,0.243768,-0.060274,0.091449,0.067645,0.112807
cep97,0.317180,1.000000,0.173086,-0.134676,0.098878,0.316891,0.366771,0.126777,-0.007433,0.201305,...,0.268167,0.032482,-0.052065,0.159405,-0.043453,0.212993,-0.051964,0.063678,0.043990,0.046383
nfkbiz,0.185087,0.173086,1.000000,0.060081,-0.022033,0.226608,0.237213,-0.013473,0.003634,0.313719,...,0.460840,0.101683,0.108600,0.296968,0.095548,0.467300,0.009655,0.121522,0.115585,-0.024784
eed,0.053960,-0.134676,0.060081,1.000000,0.147283,-0.153808,0.105175,0.275467,0.064956,0.138938,...,-0.017533,-0.019895,0.232739,-0.015923,0.344786,0.149525,0.203385,0.275390,0.235084,0.306201
hikeshi,0.175326,0.098878,-0.022033,0.147283,1.000000,0.103063,0.280626,-0.058435,0.292817,0.113320,...,0.104452,0.245086,0.180915,0.165733,0.086371,0.027839,0.027166,0.119576,0.310942,0.126126

In [5]:
# ESM
emb_sim_file="cosine_sim_mat_esm2_15B_embeddings_gene_names.csv" 
emb_sim_file_path = Path().cwd().parent / emb_sim_dir / emb_sim_file
ESM_sim_df = pd.read_csv(emb_sim_file_path, index_col=0)
ESM_sim_df.shape

(27039, 27039)

In [6]:
ESM_sim_df.head()

,si:dkey-151g10.6,sln,si:dkey-242h9.5,blacat1,ost4,tmsb4x,pmaip1,tmsb,tmsb2,LOC137487575,...,pclob,syne2b,LOC100330916,LOC141386138,col6a3,adgrf6,LOC108185957,si:ch211-250g4.3,ttn.1,ttn.2
si:dkey-151g10.6,1.000000,0.312790,0.235556,0.290776,0.314562,0.309370,0.295163,0.299036,0.309752,0.244112,...,0.329088,0.374808,0.337536,0.364947,0.368029,0.402633,0.355282,0.297613,0.313993,0.275978
sln,0.312790,1.000000,0.429107,0.486825,0.776387,0.419491,0.450646,0.406704,0.419571,0.507311,...,0.424776,0.494614,0.417537,0.270695,0.413665,0.422663,0.292567,0.470711,0.435713,0.441189
si:dkey-242h9.5,0.235556,0.429107,1.000000,0.717008,0.437563,0.353044,0.446845,0.386463,0.401738,0.810746,...,0.407050,0.458243,0.427861,0.339730,0.397162,0.399869,0.365930,0.416217,0.474932,0.508971
blacat1,0.290776,0.486825,0.717008,1.000000,0.482529,0.413111,0.482528,0.444214,0.473585,0.724885,...,0.457571,0.473893,0.425285,0.293644,0.375105,0.372552,0.330795,0.444448,0.505027,0.537901
ost4,0.314562,0.776387,0.437563,0.482529,1.000000,0.453665,0.504253,0.460988,0.489318,0.527599,...,0.457528,0.534371,0.465847,0.277950,0.467825,0.413355,0.302489,0.459441,0.487460,0.491003

### compute neighbor overlap

In [7]:
def _shared_genes(m1: pd.DataFrame, m2: pd.DataFrame) -> List[str]:
    """
    Genes must exist in BOTH index and columns for each matrix (square similarity matrix).
    Returns sorted shared genes.
    """
    g1 = set(m1.index) & set(m1.columns)
    g2 = set(m2.index) & set(m2.columns)
    shared = sorted(g1 & g2)
    if len(shared) == 0:
        raise ValueError("No shared genes found between the two matrices (considering both index and columns).")
    return shared


def _restrict_and_align(m: pd.DataFrame, genes: List[str]) -> pd.DataFrame:
    """Restrict to shared genes and enforce same ordering on rows/cols."""
    return m.loc[genes, genes]


def top_neighbors(
    sim: pd.DataFrame,
    top_n: int = 20,
    *,
    exclude_self: bool = True,
    dropna: bool = True,
) -> Dict[str, List[str]]:
    """
    For each gene (row), return the top_n most similar genes (by value).
    Assumes rows/cols are genes, but does not require symmetry.
    """
    if top_n <= 0:
        raise ValueError("top_n must be > 0")

    genes = sim.index.to_numpy()
    arr = sim.to_numpy(dtype=float, copy=True)

    # Handle NaNs
    if dropna:
        arr = np.where(np.isnan(arr), -np.inf, arr)

    # Optionally exclude self-similarity
    if exclude_self:
        np.fill_diagonal(arr, -np.inf)

    k = min(top_n, max(arr.shape[1] - (1 if exclude_self else 0), 0))
    if k == 0:
        return {g: [] for g in genes}

    # Get indices of top-k per row (fast)
    idx_part = np.argpartition(arr, -k, axis=1)[:, -k:]
    row_idx = np.arange(arr.shape[0])[:, None]
    vals = arr[row_idx, idx_part]
    order = np.argsort(vals, axis=1)[:, ::-1]  # descending
    top_idx = idx_part[row_idx, order]

    neighbors = {}
    for i, g in enumerate(genes):
        nbrs = genes[top_idx[i]].tolist()
        # If dropna=False, you might have NaNs left; filter any -inf that came from NaN exclusion
        if dropna:
            nbrs = [x for x in nbrs if np.isfinite(arr[i, np.where(genes == x)[0][0]])]
        neighbors[g] = nbrs[:k]
    return neighbors


@dataclass(frozen=True)
class OverlapResult:
    neighbor_lists_1: Dict[str, List[str]]
    neighbor_lists_2: Dict[str, List[str]]
    overlap_table: pd.DataFrame


def neighbor_overlap_between_matrices(
    m1: pd.DataFrame,
    m2: pd.DataFrame,
    *,
    top_n: int = 20,
    exclude_self: bool = True,
    dropna: bool = True,
) -> OverlapResult:
    """
    1) Find shared genes
    2) Compute top-N neighbors for each gene in each matrix
    3) Compute overlap statistics per gene

    Returns:
      - neighbor_lists_1, neighbor_lists_2: dict gene -> list of neighbors
      - overlap_table: DataFrame indexed by gene with overlap metrics
    """
    shared = _shared_genes(m1, m2)
    a = _restrict_and_align(m1, shared)
    b = _restrict_and_align(m2, shared)

    n1 = top_neighbors(a, top_n=top_n, exclude_self=exclude_self, dropna=dropna)
    n2 = top_neighbors(b, top_n=top_n, exclude_self=exclude_self, dropna=dropna)

    records = []
    for g in shared:
        s1, s2 = set(n1[g]), set(n2[g])
        inter = s1 & s2
        union = s1 | s2

        n1_count = len(s1)
        n2_count = len(s2)
        inter_count = len(inter)
        union_count = len(union)

        jaccard = inter_count / union_count if union_count else np.nan
        overlap_coeff = inter_count / min(n1_count, n2_count) if min(n1_count, n2_count) else np.nan

        records.append(
            {
                "gene": g,
                "n_neighbors_m1": n1_count,
                "n_neighbors_m2": n2_count,
                "intersection_size": inter_count,
                "union_size": union_count,
                "jaccard": jaccard,
                "overlap_coefficient": overlap_coeff,
                "shared_neighbors": sorted(inter),
            }
        )

    overlap_df = pd.DataFrame.from_records(records).set_index("gene")
    return OverlapResult(neighbor_lists_1=n1, neighbor_lists_2=n2, overlap_table=overlap_df)


# -----------------------
# Example usage:
# -----------------------
# m1 and m2 are your pairwise similarity matrices as pandas DataFrames
# result = neighbor_overlap_between_matrices(m1, m2, top_n=50)
# print(result.overlap_table.sort_values("jaccard", ascending=False).head(10))
# neighbors_for_geneX_in_m1 = result.neighbor_lists_1["GENE_X"]
# neighbors_for_geneX_in_m2 = result.neighbor_lists_2["GENE_X"]

In [8]:
result = neighbor_overlap_between_matrices(RQ_sim_df, ESM_sim_df, top_n=50)
print(result.overlap_table.sort_values("jaccard", ascending=False).head(10))

         n_neighbors_m1  n_neighbors_m2  intersection_size  union_size  \
gene
olfcq19              50              50                 45          55
olfcq16              50              50                 43          57
olfcg1               50              50                 43          57
olfcd3               50              50                 42          58
olfcg8               50              50                 42          58
olfcq3               50              50                 42          58
olfch1               50              50                 41          59
olfcq18              50              50                 41          59
olfcg9               50              50                 41          59
olfcq20              50              50                 41          59

          jaccard  overlap_coefficient  \
gene
olfcq19  0.818182                 0.90
olfcq16  0.754386                 0.86
olfcg1   0.754386                 0.86
olfcd3   0.724138                 0.84
olfcg8   0.724138                 0.84
olfcq3   0.724138                 0.84
olfch1   0.694915                 0.82
olfcq18  0.694915                 0.82
olfcg9   0.694915                 0.82
olfcq20  0.694915                 0.82

                                          shared_neighbors
gene
olfcq19  [LOC100007210, LOC103909158, LOC793043, olfcd1...
olfcq16  [LOC103909158, LOC793043, olfcd2, olfcd3, olfc...
olfcg1   [LOC100007210, LOC103909158, LOC793043, olfcd1...
olfcd3   [LOC100007210, LOC103909158, LOC793043, olfcd2...
olfcg8   [LOC103909158, LOC793043, olfcd1, olfcd2, olfc...
olfcq3   [LOC103909158, LOC793043, olfcd2, olfcd3, olfc...
olfch1   [LOC100007210, LOC103909158, LOC793043, olfcd1...
olfcq18  [LOC100007210, LOC103909158, LOC793043, olfcd1...
olfcg9   [LOC100007210, LOC103909158, LOC793043, olfcd1...
olfcq20  [LOC100007210, LOC103909158, LOC793043, olfcd1...

In [13]:
result2 = neighbor_overlap_between_matrices(RQ_sim_df, RQ_randomized_sim_df, top_n=50)
print(result2.overlap_table.sort_values("jaccard", ascending=False).head(10))

         n_neighbors_m1  n_neighbors_m2  intersection_size  union_size  \
gene
nfu1                 50              50                  3          97
actr2b               50              50                  3          97
ggact.2              50              50                  3          97
prdx6                50              50                  3          97
mppe1                50              50                  3          97
or71as2              50              50                  3          97
lmna                 50              50                  3          97
cdh1                 50              50                  3          97
pcdh12               50              50                  3          97
galnt13              50              50                  3          97

          jaccard  overlap_coefficient                   shared_neighbors
gene
nfu1     0.030928                 0.06             [gcdha, rap1ab, uhmk1]
actr2b   0.030928                 0.06             [ctns, ehbp1l1b, elk3]
ggact.2  0.030928                 0.06              [ctbs, nlrp1, qpctla]
prdx6    0.030928                 0.06              [acaa2, acp2, taldo1]
mppe1    0.030928                 0.06  [pex2, si:ch211-261p9.4, slc35b3]
or71as2  0.030928                 0.06         [or41a3, taar12a, taar14b]
lmna     0.030928                 0.06              [cdh1, elf1, mical2b]
cdh1     0.030928                 0.06            [elf1, lmna, marveld2b]
pcdh12   0.030928                 0.06             [pxdn, stab1, tmem88a]
galnt13  0.030928                 0.06             [bbs1, myo7ab, plch2a]

In [9]:
result.overlap_table.iloc[14000:14010,:]

,n_neighbors_m1,n_neighbors_m2,intersection_size,union_size,jaccard,overlap_coefficient,shared_neighbors
gene,,,,,,,
rassf7b,50,50,0,100,0.000000,0.00,[]
rassf8a,50,50,1,99,0.010101,0.02,[ppfibp1a]
rassf8b,50,50,0,100,0.000000,0.00,[]
rassf9,50,50,2,98,0.020408,0.04,"[phldb2b, wwc3]"
raver1,50,50,0,100,0.000000,0.00,[]
raver2,50,50,0,100,0.000000,0.00,[]
rb1,50,50,0,100,0.000000,0.00,[]
rb1cc1,50,50,0,100,0.000000,0.00,[]
rbbp4,50,50,1,99,0.010101,0.02,[rbbp7]
rbbp5,50,50,1,99,0.010101,0.02,[eed]

### aggregate

In [ ]:
from __future__ import annotations

import numpy as np
import pandas as pd


def _fd_bin_edges(x: np.ndarray) -> np.ndarray:
    """
    Freedman–Diaconis binning.
    Returns bin edges spanning [min, max]. Falls back to 10 bins if degenerate.
    """
    x = x[np.isfinite(x)]
    if x.size == 0:
        return np.array([0.0, 1.0])

    x_min, x_max = float(np.min(x)), float(np.max(x))
    if x_min == x_max:
        # All values identical
        return np.array([x_min, x_max + 1e-12])

    q25, q75 = np.percentile(x, [25, 75])
    iqr = q75 - q25
    if iqr <= 0:
        # fallback
        return np.linspace(x_min, x_max, 11)

    bin_width = 2 * iqr * (x.size ** (-1 / 3))
    if bin_width <= 0:
        return np.linspace(x_min, x_max, 11)

    n_bins = int(np.ceil((x_max - x_min) / bin_width))
    n_bins = max(n_bins, 1)
    return np.linspace(x_min, x_max, n_bins + 1)


def summarize_jaccard_bins(
    overlap: pd.DataFrame | pd.Series,
    *,
    jaccard_col: str = "jaccard",
    method: str = "linspace_0_1",  # "manual", "linspace_0_1", "linspace_data", "fd", "quantile"
    n_bins: int = 10,
    bin_edges: list[float] | np.ndarray | None = None,  # used for method="manual"
    dropna: bool = True,
    right: bool = True,
    include_lowest: bool = True,
) -> pd.DataFrame:
    """
    Summarize how many genes fall into Jaccard bins.

    Parameters
    ----------
    overlap : DataFrame or Series
        If DataFrame: uses overlap[jaccard_col]. If Series: uses it directly.
    method : str
        - "manual": use bin_edges you pass in
        - "linspace_0_1": uniform bins from 0 to 1 (good for Jaccard)
        - "linspace_data": uniform bins from min(x) to max(x)
        - "fd": Freedman–Diaconis bins (data-driven width)
        - "quantile": equal-frequency bins (pd.qcut)
    n_bins : int
        Number of bins (used for linspace_* / quantile; fd chooses its own)
    bin_edges : list/ndarray
        Required for method="manual"
    """
    if isinstance(overlap, pd.DataFrame):
        x = overlap[jaccard_col].astype(float)
    else:
        x = overlap.astype(float)

    if dropna:
        x = x.dropna()

    if method == "quantile":
        # qcut can fail if many identical values; duplicates="drop" prevents crashing
        cats = pd.qcut(x, q=min(n_bins, max(len(x), 1)), duplicates="drop")
        binned = cats

    else:
        if method == "manual":
            if bin_edges is None:
                raise ValueError('method="manual" requires bin_edges=[...]')
            edges = np.asarray(bin_edges, dtype=float)

        elif method == "linspace_0_1":
            edges = np.linspace(0.0, 1.0, n_bins + 1)

        elif method == "linspace_data":
            if len(x) == 0:
                edges = np.array([0.0, 1.0])
            else:
                edges = np.linspace(float(x.min()), float(x.max()), n_bins + 1)

        elif method == "fd":
            edges = _fd_bin_edges(x.to_numpy())

        else:
            raise ValueError(f"Unknown method: {method}")

        binned = pd.cut(
            x,
            bins=edges,
            right=right,
            include_lowest=include_lowest,
        )

    out = (
        binned.value_counts(sort=False, dropna=False)
        .rename("count")
        .to_frame()
        .assign(
            fraction=lambda d: d["count"] / d["count"].sum() if d["count"].sum() else np.nan,
            cumulative_count=lambda d: d["count"].cumsum(),
            cumulative_fraction=lambda d: d["fraction"].cumsum(),
        )
        .reset_index()
        .rename(columns={"index": "bin"})
    )
    return out

In [12]:

# 1) Uniform bins from 0 to 1 (common for Jaccard)
summary = summarize_jaccard_bins(result.overlap_table, method="linspace_0_1", n_bins=20)
summary

           jaccard  count  fraction  cumulative_count  cumulative_fraction
0   (-0.001, 0.05]  19303  0.885581             19303             0.885581
1      (0.05, 0.1]   1457  0.066844             20760             0.952425
2      (0.1, 0.15]    412  0.018902             21172             0.971326
3      (0.15, 0.2]    205  0.009405             21377             0.980731
4      (0.2, 0.25]    169  0.007753             21546             0.988485
5      (0.25, 0.3]     60  0.002753             21606             0.991237
6      (0.3, 0.35]     32  0.001468             21638             0.992705
7      (0.35, 0.4]     36  0.001652             21674             0.994357
8      (0.4, 0.45]     57  0.002615             21731             0.996972
9      (0.45, 0.5]     27  0.001239             21758             0.998211
10     (0.5, 0.55]     11  0.000505             21769             0.998715
11     (0.55, 0.6]      9  0.000413             21778             0.999128
12     (0.6, 0.65]      6  0.000275             21784             0.999404
13     (0.65, 0.7]      7  0.000321             21791             0.999725
14     (0.7, 0.75]      3  0.000138             21794             0.999862
15     (0.75, 0.8]      2  0.000092             21796             0.999954
16     (0.8, 0.85]      1  0.000046             21797             1.000000
17     (0.85, 0.9]      0  0.000000             21797             1.000000
18     (0.9, 0.95]      0  0.000000             21797             1.000000
19     (0.95, 1.0]      0  0.000000             21797             1.000000

In [17]:
result2.overlap_table.jaccard.describe()

count    22011.000000
mean         0.001096
std          0.003383
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          0.030928
Name: jaccard, dtype: float64

In [14]:

# 1) Uniform bins from 0 to 1 (common for Jaccard)
summary2 = summarize_jaccard_bins(result2.overlap_table, method="linspace_0_1", n_bins=20)
summary2

           jaccard  count  fraction  cumulative_count  cumulative_fraction
0   (-0.001, 0.05]  22011       1.0             22011                  1.0
1      (0.05, 0.1]      0       0.0             22011                  1.0
2      (0.1, 0.15]      0       0.0             22011                  1.0
3      (0.15, 0.2]      0       0.0             22011                  1.0
4      (0.2, 0.25]      0       0.0             22011                  1.0
5      (0.25, 0.3]      0       0.0             22011                  1.0
6      (0.3, 0.35]      0       0.0             22011                  1.0
7      (0.35, 0.4]      0       0.0             22011                  1.0
8      (0.4, 0.45]      0       0.0             22011                  1.0
9      (0.45, 0.5]      0       0.0             22011                  1.0
10     (0.5, 0.55]      0       0.0             22011                  1.0
11     (0.55, 0.6]      0       0.0             22011                  1.0
12     (0.6, 0.65]      0       0.0             22011                  1.0
13     (0.65, 0.7]      0       0.0             22011                  1.0
14     (0.7, 0.75]      0       0.0             22011                  1.0
15     (0.75, 0.8]      0       0.0             22011                  1.0
16     (0.8, 0.85]      0       0.0             22011                  1.0
17     (0.85, 0.9]      0       0.0             22011                  1.0
18     (0.9, 0.95]      0       0.0             22011                  1.0
19     (0.95, 1.0]      0       0.0             22011                  1.0

In [21]:

# 2) Manual bins (you choose edges)
edges = [0, 0.03, 0.1, 0.2, 0.5, 0.7,0.9]
summary = summarize_jaccard_bins(result.overlap_table, method="manual", bin_edges=edges)
summary

          jaccard  count  fraction  cumulative_count  cumulative_fraction
0  (-0.001, 0.03]  17170  0.787723             17170             0.787723
1     (0.03, 0.1]   3590  0.164702             20760             0.952425
2      (0.1, 0.2]    617  0.028307             21377             0.980731
3      (0.2, 0.5]    381  0.017479             21758             0.998211
4      (0.5, 0.7]     33  0.001514             21791             0.999725
5      (0.7, 0.9]      6  0.000275             21797             1.000000

In [27]:
## print out the rows where jaccard >0.7
result.overlap_table[result.overlap_table.jaccard > 0.7]

,n_neighbors_m1,n_neighbors_m2,intersection_size,union_size,jaccard,overlap_coefficient,shared_neighbors
gene,,,,,,,
olfcd3,50,50,42,58,0.724138,0.84,"[LOC100007210, LOC103909158, LOC793043, olfcd2..."
olfcg1,50,50,43,57,0.754386,0.86,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcg8,50,50,42,58,0.724138,0.84,"[LOC103909158, LOC793043, olfcd1, olfcd2, olfc..."
olfcq16,50,50,43,57,0.754386,0.86,"[LOC103909158, LOC793043, olfcd2, olfcd3, olfc..."
olfcq19,50,50,45,55,0.818182,0.90,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcq3,50,50,42,58,0.724138,0.84,"[LOC103909158, LOC793043, olfcd2, olfcd3, olfc..."

In [30]:
## print out the rows where jaccard between 0.5 and 0.7
result.overlap_table[(result.overlap_table.jaccard > 0.5) & (result.overlap_table.jaccard < 0.7)]

,n_neighbors_m1,n_neighbors_m2,intersection_size,union_size,jaccard,overlap_coefficient,shared_neighbors
gene,,,,,,,
LOC793043,50,50,36,64,0.562500,0.72,"[LOC103909158, olfcd1, olfcd2, olfcd3, olfcg1,..."
crygm2d14,50,50,34,66,0.515152,0.68,"[cryba1a, cryba1b, cryba1l2, cryba2a, cryba2b,..."
crygm2d15,50,50,35,65,0.538462,0.70,"[cryba1b, cryba1l2, cryba2a, cryba2b, crygm1, ..."
crygm2d4,50,50,34,66,0.515152,0.68,"[cryba1b, cryba2a, cryba2b, crygm1, crygm2b, c..."
crygm2f,50,50,39,61,0.639344,0.78,"[cryba1a, cryba1b, cryba1l2, crygm1, crygm2a, ..."
crygm5,50,50,34,66,0.515152,0.68,"[cryba1b, cryba1l2, cryba2a, cryba2b, crygm1, ..."
olfcd2,50,50,37,63,0.587302,0.74,"[LOC103909158, LOC793043, olfcd3, olfce1p, olf..."
olfce1p,50,50,39,61,0.639344,0.78,"[LOC100007210, LOC103909158, olfcd1, olfcd2, o..."
olfcg3,50,50,36,64,0.562500,0.72,"[LOC100007210, LOC793043, olfcd1, olfcd2, olfc..."
olfcg9,50,50,41,59,0.694915,0.82,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfch1,50,50,41,59,0.694915,0.82,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcj1,50,50,34,66,0.515152,0.68,"[LOC103909158, LOC793043, olfcd2, olfcd3, olfc..."
olfck2,50,50,34,66,0.515152,0.68,"[LOC103909158, LOC793043, olfcd2, olfcd3, olfc..."
olfcq1,50,50,35,65,0.538462,0.70,"[LOC103909158, olfcd2, olfcd3, olfce1p, olfce2..."
olfcq10,50,50,36,64,0.562500,0.72,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcq11,50,50,40,60,0.666667,0.80,"[LOC100007210, LOC103909158, olfcd1, olfcd2, o..."
olfcq13,50,50,39,61,0.639344,0.78,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcq14,50,50,37,63,0.587302,0.74,"[LOC100007210, LOC793043, olfcd1, olfcd2, olfc..."
olfcq15,50,50,36,64,0.562500,0.72,"[LOC100007210, olfcd1, olfcd2, olfcd3, olfce1p..."
olfcq17,50,50,35,65,0.538462,0.70,"[LOC100007210, LOC793043, olfcd1, olfcd2, olfc..."
olfcq18,50,50,41,59,0.694915,0.82,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcq2,50,50,35,65,0.538462,0.70,"[LOC103909158, LOC793043, olfcd2, olfcd3, olfc..."
olfcq20,50,50,41,59,0.694915,0.82,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcq4,50,50,34,66,0.515152,0.68,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcq6,50,50,37,63,0.587302,0.74,"[LOC100007210, LOC793043, olfcd1, olfcd2, olfc..."
olfcq8,50,50,36,64,0.562500,0.72,"[LOC100007210, olfcd1, olfcd2, olfcd3, olfce1p..."
olfcq9,50,50,36,64,0.562500,0.72,"[LOC100007210, LOC793043, olfcd1, olfcd2, olfc..."
olfcs1,50,50,38,62,0.612903,0.76,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcu1,50,50,34,66,0.515152,0.68,"[LOC103909158, LOC793043, olfcd2, olfcd3, olfc..."
olfcv1,50,50,40,60,0.666667,0.80,"[LOC100007210, LOC103909158, LOC793043, olfcd1..."
olfcx1,50,50,39,61,0.639344,0.78,"[LOC100007210, LOC793043, olfcd1, olfcd2, olfc..."
olfcx2,50,50,40,60,0.666667,0.80,"[LOC103909158, LOC793043, olfcd2, olfcd3, olfc..."
olfcx3,50,50,38,62,0.612903,0.76,"[LOC103909158, LOC793043, olfcd2, olfcd3, olfc..."

In [34]:
## print out the rows where jaccard between 0.2 and 0.5
tmp_df = result.overlap_table[(result.overlap_table.jaccard > 0.2) & (result.overlap_table.jaccard < 0.5)]
tmp_df.head()
tmp_df.shape
tmp_df.to_csv("tmp_df.csv")